### ISSUE TITLE
Actual UTF symbols instead of \uXXX

### ISSUE THREAD

**Issue by limonte** [hCaptcha/hcaptcha-i18n#10]
It is currently **very hard to contribute** to this repo because locales are stored in a weird format. I believe there are technical reasons for that, but is it possible to have actual UTF symbols instead of \uXXX in locales?

**Comment by gaieges** [comment]
We do prefer the `\u` strings, but you can contribute either rendered symbols *or* unicode hex.  

FWIW This can also be done via a quick browser function:

<img width="458" alt="Screen Shot 2020-08-26 at 11 11 38 AM" src="https://user-images.githubusercontent.com/6024347/91328854-0ea01a80-e78d-11ea-9ae4-1d060ad0cc85.png">

**Comment by e271828-** [comment]
@gaieges Maybe add an example conversion JS function for folks to the README? I think we store it this way for performance reasons, but no reason someone translating strings has to think about it.

**Comment by limonte** [comment]
Thank you for the reply. I'm pretty sure that you're using Google Translate for translations and therefore the quality is very low for now.

The only chance to improve translations is to engage native speakers and be as friendly as possible for them and make the contribution process as easy as editing files in GitHub.

With this `\u` madness I'm pretty sure you'll have no help from the community and the i18n of hcaptcha will have very low quality.

**Comment by e271828-** [comment]
@gaieges Maybe we should just convert these at build time, rather than storing the JS escaped forms here. I do agree it's more work to edit than necessary.

**Comment by gaieges** [comment]
Please re-read what I originally wrote: 

> you can contribute either rendered symbols or unicode hex.

Happy to write a function/converter too, but it shouldn't matter here from a community perspective. 

Send whatever you'd like!

**Comment by limonte** [comment]
I read that carefully. Here's what you're missing. I'm the native Russian, Serbian and Croatian speaker.

As the developer who is using the hCaptcha I want to improve the UX for my users and also pay back to hCaptcha with my contributions.

If locales would contain rendered symbols, I would go through the whole file and fix **all issues** in them. hCaptcha would definitely benefit from that as well as hCaptcha's users.

Right now I can contribute with fixing a couple of strings and that'd be 10x more difficult than it should be.

**Comment by gaieges** [comment]
Ahh thats a great idea, that we should do @e271828-
