### ISSUE TITLE
Italian translations are unclear

### ISSUE THREAD

**Issue by Xring-git** [hCaptcha/hcaptcha-i18n#14]
Hi,

I wanted to point out that the Italian translations are unclear, just to give an example: "Privacy Policy" is NOT "vita privata" (that means “Private life”) but in Italian it can remain "Privacy Policy" or "Privacy".

If you want, I can check all italian trtaslations.

Franco

**Comment by e271828-** [comment]
@Xring-git sure, just open up a PR with any changes. Appreciate it!
