### ISSUE TITLE
Translation improvements for hcaptcha challenge

### ISSUE THREAD

**Issue by jarek-kurz** [hCaptcha/hcaptcha-i18n#19]
During the implementation of hcaptcha in PL lang we notice that some translations are not correct or should be changed to a better understanding.

As a user, I would like to see a correct translation in hcaptcha challenges, so I will understood what needs to be done on that modal. 

**AC**
1. copy "Zaznacz wszystkie obrazy zawierające $name_of_the_thing$” should be changed to 
 Wybierz wszystkie obrazy zawierające $name_of_the_thing$
pls check the screenshot and point no 1.
$name_of_the_thing$ - I guess that this is a differnt translation and chose randomly 

2.  copy "Jeśli nie ma, kliknij Pomiń” should be changed to 
 Jeśli nie widzisz tego elementu, kliknij “Pomiń"
pls check the screenshot and point no 2.

3. copy "Pominąć” should be changed to 
Pomiń
pls check the screenshot and point no 3.

4. copy "Kolejny” should be changed to 
Przejdź dalej
pls check the screenshot and point no 3.

5. copy "Sprawdź” should be changed to 
Weryfikuj
pls check the screenshot and point no 3.

![challange=hcaptcha](https://user-images.githubusercontent.com/72490626/95301247-a27eff00-0880-11eb-98c2-94c4a61cf458.png)

**Comment by e271828-** [comment]
@jarek-kurz thanks for the report. #20 should solve most of this shortly. 1 will take slightly longer to take effect.

**Comment by jarek-kurz** [comment]
@e271828- we checked the translations and notice that AC 1 is still not done. Could you r re-do AC1?
