### ISSUE TITLE
Bugs in "report an error" window in Hcaptcha challenge

### ISSUE THREAD

**Issue by jarek-kurz** [hCaptcha/hcaptcha-i18n#22]
During testing the Hcaptcha modal we notice that there are some bugs with the new window when clicking on "report an error" (menu icon on the left bottom corner).

AC
- [ ] 1. Wysłać should be changed to "Wyślij"
- [x] 2. "Off screen" needs new translation. Could you point what does it mean?
- [x] 3. When choosing "Inny" (different) there is no margin on the bottom

pls check screenshots
![bandicam 2020-10-15 12-52-19-019](https://user-images.githubusercontent.com/72490626/96576646-c3107580-12d2-11eb-9bfa-6bb3a9fcb6c3.jpg)

![bandicam 2020-10-15 12-46-36-624](https://user-images.githubusercontent.com/72490626/96576669-cc014700-12d2-11eb-8489-8f266adc93d7.jpg)

**Comment by e271828-** [comment]
@jarek-kurz thanks for the report! "Off Screen" means "modal was obscured."

**Comment by e271828-** [comment]
2 & 3 are now addressed:

<img width="344" alt="Screen Shot 2020-10-20 at 3 13 31 PM" src="https://user-images.githubusercontent.com/7109823/96650002-f1984b80-12e6-11eb-9396-c7d56aad647c.png">

**Comment by jarek-kurz** [comment]
@e271828- thx for changing the translations, what about AC1? Will you change it also

**Comment by e271828-** [comment]
@jarek-kurz AC1 has been merged in #23 and will likely be deployed later today.
