### ISSUE TITLE
Update the UI to avoid getting the buttons truncated

### ISSUE THREAD

**Issue by xllrsrz** [hCaptcha/hcaptcha-i18n#44]
Truncated buttons at Report Bug -> Select “Other (Inny)” -> Observe buttons at the bottom part of the popup window (screenshot is attached below)

![image](https://user-images.githubusercontent.com/78567372/106962974-db6da880-677a-11eb-8e5e-3650f881615c.png)

**Comment by e271828-** [comment]
Closed in #746 (internal ref)
